### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by Th3lazykid** [Emoe/OpenBugBounty-Scrapper#2]
### Can you help me solve this error, please? Confused!

<img width="1006" alt="Screenshot 2020-07-27 at 6 33 18 PM" src="https://user-images.githubusercontent.com/56188454/88544948-e0b5a200-d037-11ea-9c73-80f4741fc4de.png">

**Comment by Emoe** [comment]
Sorry for the late response. Should now be fixed.
